### ISSUE TITLE
Stop Colly visiting other attributes with break statement

### ISSUE THREAD

**Issue by Frodgy** [asciimoo/colly#26] opened 2017-10-13 02:48 UTC

**Comment by asciimoo** [comment] 2017-10-13 09:25
Could you please describe this a bit more? Do you have example code to demonstrate the desired behavior?

**Comment by Frodgy** [comment] 2017-10-13 09:34
```
	c.OnHTML("a", func(e *colly.HTMLElement) {
		if e.Attr("title") == "The only needed title" {
			link = e.Attr("href")
			break // stop searching for other "a" tags
		}
	})
```

**Comment by asciimoo** [comment] 2017-10-13 10:25
@Frodgy I can't see how this could be implemented without changing the signature of the OnHTML callback, but you can handle these cases without the requested change.

Example 1 (select only those a elements which have title attribute):
```go
c.OnHTML("a[title]", func(e *colly.HTMLElement) {
	link = e.Attr("href")
})
```

Example 2 (handle break from your code):
```go
visited := false
c.OnHTML("a", func(e *colly.HTMLElement) {
	if visited {
		return
	}
	if e.Attr("title") == "The only needed title" {
		link = e.Attr("href")
		visited = true
	}
})
```

**Comment by asciimoo** [comment] 2017-10-13 10:43
@Frodgy I'm closing this issue, feel free to reopen if neither of the above suggestions solves your problem.

**Closed by asciimoo** 2017-10-13 10:43 UTC

**Comment by nikneym** [comment] 2023-01-26 08:58
Hi, I'm dealing with similar situation. I only want to get first 5 elements and discard the rest. This is how I deal with it currently:
```go
var items [5]book
pos := 0
c.OnHTML("...", func(e *colly.HTMLElement) {
	if pos == len(items)
		return
	}

	name := e.ChildText(".name")
	author := e.ChildText(".author span a span")
	publisher := e.ChildText(".publisher")
	image := e.ChildAttr(".image .cover img", "src")
	price := e.ChildText(".price-new span.value, .price-old span.value")

	items[pos] = book{Name: name, Author: author, Publisher: publisher, Cover: image, Price: price}
	pos++
})
```
This is works as intended but a solution like `goquery.EachWithBreak` would suit better. Also it'd be nice to reach number of element as a function argument.
